# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QS3B-DJzmYpFa-pllyFaqOw1Ap5qHQ3
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Konfigurasi halaman
st.set_page_config(page_title="Beijing Air Quality Dashboard", layout="wide")

# Fungsi untuk memuat data (Gunakan file main_data.csv yang sudah didownload dari Colab)
@st.cache_data
def load_data():
    df = pd.read_csv("main_data.csv")
    df['datetime'] = pd.to_datetime(df['datetime'])
    return df

# Memuat data
try:
    df = load_data()
except Exception as e:
    st.error("Gagal memuat data. Pastikan file 'main_data.csv' berada di direktori yang sama.")
    st.stop()

# --- SIDEBAR ---
st.sidebar.image("https://raw.githubusercontent.com/streamlit/norm-vizz/main/static/vizz_logo.png", width=100)
st.sidebar.title("Filter Analisis")
st.sidebar.markdown("Pilih stasiun untuk melihat detail spesifik:")

# Filter Stasiun
station_list = df['station'].unique()
selected_stations = st.sidebar.multiselect(
    "Stasiun:",
    options=station_list,
    default=station_list[:3]
)

# Filter Data Berdasarkan Sidebar
df_filtered = df[df['station'].isin(selected_stations)]

# --- MAIN PAGE ---
st.title("🌬️ Air Quality Analysis Dashboard: Beijing")
st.markdown(f"**Nama:** Muhammad Ruben Farras | **Dataset:** Air Quality (2013-2017)")

# Row 1: Key Metrics
st.subheader("Ringkasan Kualitas Udara (Rata-rata)")
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("PM2.5", f"{df_filtered['PM2.5'].mean():.2f} µg/m³")
with col2:
    st.metric("CO", f"{df_filtered['CO'].mean():.2f} µg/m³")
with col3:
    st.metric("NO2", f"{df_filtered['NO2'].mean():.2f} µg/m³")

st.divider()

# Row 2: Pertanyaan 1 - Korelasi
st.subheader("1. Hubungan Antar Polutan (Insight Korelasi)")
col_a, col_b = st.columns([2, 1])

with col_a:
    fig, ax = plt.subplots(figsize=(8, 5))
    corr_matrix = df[['PM2.5', 'CO', 'NO2', 'TEMP', 'RAIN']].corr()
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", ax=ax)
    st.pyplot(fig)

with col_b:
    st.info("""
    **Analisis Korelasi:**
    Terdapat korelasi positif yang sangat kuat (0.77) antara **PM2.5** dan **CO**.
    Hal ini membuktikan bahwa emisi pembakaran (kendaraan/industri) adalah faktor utama polusi udara.
    """)

# Row 3: Pertanyaan 2 - Perbandingan Stasiun
st.subheader("2. Peta Polusi Berdasarkan Wilayah (Stasiun)")
fig2, ax2 = plt.subplots(figsize=(10, 5))
station_rank = df.groupby('station')['PM2.5'].mean().sort_values(ascending=False).reset_index()
sns.barplot(x='PM2.5', y='station', data=station_rank, palette='viridis', ax=ax2)
ax2.set_title("Rata-rata PM2.5 per Stasiun di Beijing")
st.pyplot(fig2)

# Row 4: Machine Learning Insight (Optional)
st.divider()
st.subheader("🤖 Machine Learning Insight (Linear Regression)")
st.write("Model regresi menunjukkan bahwa variabel CO dan NO2 dapat menjelaskan variasi PM2.5 secara signifikan.")
st.markdown("> **Hasil Model:** Kenaikan kadar CO dan NO2 memberikan dampak linear terhadap lonjakan PM2.5 di seluruh wilayah Beijing.")

st.sidebar.caption("Submission: Dicoding Data Analysis")